"""add seen column

Revision ID: 5b365e5965de
Revises: 2fab0edcdad0
Create Date: 2026-07-31 20:56:44.080233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b365e5965de'
down_revision: Union[str, None] = '2fab0edcdad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('seen_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'seen_at')
    # ### end Alembic commands ###
